version: '3'

services:
  guardian-service:
    container_name: guardian-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 12001:5000
    networks:
      - networks-guardian-service
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai

  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=Test
      - TZ=Asia/Shanghai
    networks:
      - networks-guardian-service
    volumes:
      - db_data:/data/db

volumes:
  db_data:

networks:
  networks-guardian-service:
