version: '3'

services:
  guardian-service:
    container_name: guardian-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 12001:5000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai

