version: '3'

services:
  guardian-service:
    container_name: guardian-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 12001:5000
	  - 13306:13306
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai

